[theme]
primaryColor = "#f1c40f"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e2130"
textColor = "#fafafa"
base = "dark"

[client]
# Isso ajuda a remover elementos de interface do Streamlit
toolbarMode = "viewer"
showSidebarNavigation = true